# Generated by Django 4.2.8 on 2023-12-19 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('fullname', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('attachment', models.FileField(max_length=500, upload_to='img')),
                ('link_1', models.CharField(max_length=50)),
                ('link_2', models.CharField(max_length=50)),
                ('link_3', models.CharField(max_length=50)),
                ('selfie', models.FileField(max_length=500, upload_to='img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
